services:
  - type: web
    name: mymsce
    runtime: python
    repo: https://github.com/einzmo/joka
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app